server:
  port: 9090
spring:
  security:
    oauth2:
      client:
        registration:
          linkedin:
            client-id: ${LINKEDIN_CLIENT_ID}
            client-secret: ${LINKEDIN_CLIENT_SECRET}
            client-name: LinkedIn
            provider: linkedin
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - r_liteprofile
              - r_emailaddress
            client-authentication-method: client_secret_post
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            user-name-attribute: id
  datasource:
    generate-unique-name: false
    name: tacocloud
    jndi-name: java:/comp/env/jdbc/tacoCloudDS

logging:
  file:
    name: TacoCloud.log
    path: /var/logs/
  level:
    root: warn
    org:
      springframework:
        security: debug

greeting:
  welcome: You are using ${spring.application.name}

taco:
  orders:
    page-size: 10

---
spring:
  profiles:
    prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: warn