spring:
  application:
    name: authorization-server

  datasource:
    url= jdbc:h2:file:./data/authdb
    driverClassName=org.h2.Driver
    username=sa
    password=

  jpa:
    hibernate:
      ddl-auto=update
      show-sql=true

    h2:
      console:
        enabled= true
        path= /h2-console
      settings:
        web-allow-others= true

server:
  port: 9000